### ISSUE TITLE
Lecroy Wavepro 7300A

### ISSUE THREAD

**Issue by arbite** [glscopeclient/scopehal-fwp-bridge#1]
Hiya,
I have a Wavepro 7300a. It's an old beast, running Windows XP, but it does have XDEV and from what I can see FastWavePort.
Do you imagine fwp-bridge will run on XP, given that I can actually compile it?
I develop on the Linux and my Windows dev chops are pretty nonexistent. Can you give any advice on compiling under XP, or point me to anyone else that has done so?
Thanks very much

**Comment by azonenberg** [comment]
AFAIK nobody else has tried the FWP bridge other than myself. I developed and tested it on a SDA 816Zi-A running Win10.

Have you tried the vanilla scopehal "lecroy" driver on your scope yet? You will probably have to add some model detection code to make it work properly as there were a a few breaking API changes between the XP era and modern scopes. I just helped a friend get her DDA 5005A running XP working with scopehal last week, though, so most of the code is already there. You'll likely just have to add a few model ID checks to trigger the old/new code path appropriately for your model.

**Comment by arbite** [comment]
Hey, No I haven't tried the vanilla scopehal yet, but it seem like the best approach to start with. I'll give that a try and see how I get on. Thanks!

**Comment by azonenberg** [comment]
The FWP driver is derived from the vanilla driver and just accelerates waveform download. All of the control plane traffic still uses the same SCPI commands so get that working first.

**Comment by arbite** [comment]
Thanks, I've managed to connect to it via VICP. I am getting some errors eg:
```
Warning: Unknown trigger type "EDGE"
Warning: Unimplemented stream type 7, don't know how to render it
```
I'll have a dig around. It looks like my oscilloscope might support a subset of VICP, or its a bit different. I'll try and find the manual or online help to see what is actually supported.

**Comment by azonenberg** [comment]
> Thanks, I've managed to connect to it via VICP. I am getting some errors eg:
> 
> ```
> Warning: Unknown trigger type "EDGE"
> Warning: Unimplemented stream type 7, don't know how to render it
> ```
> 
> I'll have a dig around. It looks like my oscilloscope might support a subset of VICP, or its a bit different. I'll try and find the manual or online help to see what is actually supported.

File a separate ticket against scopehal for any driver issues and let's close this one, since at least as of now you're not having bridge problems.

Also make sure you're running latest. The DDA5005A fixes landed just a day or two ago and it exhibited very similar failures to what you're seeing (they changed trigger types from all caps to camel case some time in the XP to Vista transition and we did case sensitive comparisons in the driver).

**Comment by arbite** [comment]
No problems. Just to clear up - latest as in master branch?

**Comment by azonenberg** [comment]
Yep. At this stage of maturity you should pretty much always be running latest from master. We haven't had an official release yet (although we're working our way to one hopefully soon?) and new bugfixes and features are added on a daily basis. Any regressions should be found and noticed quickly.

**Comment by arbite** [comment]
Sweet, I can see the DDA5005 changes in the master commits. I'll update and see how I get on. Closing this off now. Thanks again
